server:
  port: 8003
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
zuul:
  routes:
    provider: /p/**
    #zuul.routes.provider：给服务提供者 provider 设置映射